# Manifest for this project. See https://luaupm.com/docs
# Add dependencies with `embr add <scope/name>`, then run `embr install`.

[indices]
wally = "https://github.com/UpliftGames/wally-index"
pesde = "https://github.com/pesde-pkg/index"

[dependencies]
core = { name = "chief/core", version = "^" }
vow = { name = "synttx/vow", version = "^", index = "wally" }

[tools]
larvae = "larvae-luau/larvae@0.5.0"
rojo = "rojo-rbx/rojo@7.7.0"
rogen = "ldgerrits/rogen@1.4.3"
blink = "1Axen/blink@0.18.8"
lest = "lest-luau/lest@0.5.0"

[scripts]
build = "rojo build .larvae/build.project.json -o build.rbxl"
sourcemap = "rojo sourcemap default.project.json --output sourcemap.json"
serve = ["lpm run sourcemap", "larvae process -w", "rogen watch", "rojo serve .larvae/build.project.json"]
