name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Ember
        run: |
          curl -fsSL -o embr-linux https://github.com/luaupm/cli/releases/latest/download/embr-linux-x86_64
          chmod +x embr-linux
          ./embr-linux self install
          echo "$HOME/.ember/bin" >> "$GITHUB_PATH"

      - name: Cache Ember
        uses: actions/cache@v6
        with:
          path: |
            ~/.ember/archive-cache
            ~/.ember/index-cache
          key: ember-archives-${{ runner.os }}-${{ hashFiles('ember.lock') }}
          restore-keys: ember-archives-${{ runner.os }}-

      - name: Install packages and tools
        run: embr install --locked

      - name: Format
        run: larvae fmt --check

      - name: Lint
        run: larvae lint

      - name: Check
        run: larvae check

      - name: Build
        run: |
          larvae process
          rogen
          rojo build .larvae/build.project.json --output game.rbxl

      - name: Tests
        run: lest